import Head from 'next/head'
import { Inter } from 'next/font/google'
import Avatar from '../../components/Avatar'
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Image</p>

          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />

          <Avatar url="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50" />
        </div>
      </header>
      {/* body */}
      {/* Footer */}
    </>
  )
}
